# Generated by Django 3.2.7 on 2022-08-31 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('category', models.CharField(max_length=20)),
                ('color', models.CharField(max_length=20)),
                ('city', models.CharField(max_length=20)),
                ('price', models.IntegerField()),
            ],
        ),
    ]
